import { useState } from 'react'
import { UserRound, Phone, MapPinned, Coins, Landmark, WalletCards, FileCheck2, ShieldCheck, ArrowRight, Check, ExternalLink, Sparkles, CircleDollarSign } from 'lucide-react'

const FORM_URL = 'https://docs.google.com/forms/d/e/1FAIpQLSdyVSKymLVij2aCDVk1ewr29_mF0Zij6hX0e6yjS3smJro_xw/viewform'

const formJourney = [
  { id: 'profile', step: '01', title: 'Applicant details', detail: 'Basic applicant identity and contact information', icon: UserRound },
  { id: 'contact', step: '02', title: 'Contact & location', detail: 'Phone, location and preferred contact context', icon: Phone },
  { id: 'category', step: '03', title: 'Evaluation category', detail: 'Physical Gold, Capital / Money, Land & Property or Financial Assets', icon: Coins },
  { id: 'asset', step: '04', title: 'Asset information', detail: 'Details needed to understand the asset or value being presented', icon: Landmark },
  { id: 'value', step: '05', title: 'Value & requirement', detail: 'Indicative value and the requirement you want evaluated', icon: CircleDollarSign },
  { id: 'review', step: '06', title: 'Declaration & submission', detail: 'Review the information and submit through the official Google Form', icon: FileCheck2 }
]

const options = [
  { id: 'gold', title: 'Physical Gold', subtitle: 'Gold / Jewellery', icon: Coins, visual: 'Gold', description: 'Eligible physical gold or jewellery holdings.' },
  { id: 'capital', title: 'Capital / Money', subtitle: 'Capital-based option', icon: WalletCards, visual: 'Capital', description: 'Capital-based business interest option.' },
  { id: 'land', title: 'Land & Property', subtitle: 'Land / commercial property', icon: MapPinned, visual: 'Property', description: 'Eligible land or property-related value.' },
  { id: 'financial', title: 'Financial Assets', subtitle: 'Other financial assets', icon: Landmark, visual: 'Financial', description: 'Other eligible financial assets.' }
]

export default function EligibilityFormPage() {
  const [selected, setSelected] = useState('gold')
  const active = options.find((item) => item.id === selected) || options[0]
  const ActiveIcon = active.icon
  const openForm = () => window.location.assign(FORM_URL)

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-10">
      <section className="text-center max-w-4xl mx-auto space-y-4 future-reveal">
        <span className="inline-flex items-center gap-2 rounded-full border border-amber-400/30 bg-amber-400/10 px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-300"><ShieldCheck className="h-3.5 w-3.5" /> Preliminary Evaluation</span>
        <h1 className="text-3xl sm:text-5xl font-extrabold font-serif-brand text-white">Start your Sree Vriddhi evaluation</h1>
        <p className="text-sm sm:text-base leading-7 text-slate-300">Understand the information journey before you open the official evaluation form. The visual below represents the form flow, while the Google Form remains the authoritative source for the actual questions and submission.</p>
      </section>
      <section className="relative overflow-hidden rounded-[2rem] border border-amber-400/20 bg-slate-950/90 p-5 sm:p-8 shadow-2xl" data-future-tilt>
        <div className="pointer-events-none absolute -left-28 -top-28 h-72 w-72 rounded-full bg-amber-400/10 blur-3xl" /><div className="pointer-events-none absolute -right-28 -bottom-28 h-72 w-72 rounded-full bg-cyan-400/5 blur-3xl" />
        <div className="relative grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]">
          <div className="flex justify-center"><div className="relative h-[320px] w-[320px] sm:h-[390px] sm:w-[390px] [perspective:1400px]">
            <div className="absolute inset-[7%] rounded-[3rem] border border-amber-400/20 bg-amber-400/[.025] [transform:rotateX(58deg)_rotateZ(-12deg)] shadow-[0_0_90px_rgba(245,158,11,.12)]" /><div className="absolute inset-[15%] rounded-[2.5rem] border border-cyan-400/10 bg-cyan-400/[.02] [transform:rotateX(58deg)_rotateZ(14deg)]" /><div className="absolute inset-[25%] rounded-[2rem] border border-slate-700/80 bg-slate-950/95 shadow-[0_30px_100px_rgba(0,0,0,.55)] [transform:rotateX(10deg)_rotateY(-8deg)_translateZ(35px)]" />
            <div className="absolute inset-[31%] flex flex-col items-center justify-center rounded-[1.5rem] border border-amber-300/40 bg-slate-950/95 p-5 text-center shadow-[0_0_60px_rgba(245,158,11,.12)] [transform:translateZ(75px)]"><ActiveIcon className="h-9 w-9 text-amber-300" /><span className="mt-3 text-lg font-extrabold text-white">{active.visual}</span><span className="mt-1 text-[9px] uppercase tracking-[.18em] text-amber-200">Selected evaluation</span><div className="mt-4 h-1 w-20 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-2/3 rounded-full bg-gradient-to-r from-amber-400 to-cyan-300" /></div><Sparkles className="mt-4 h-4 w-4 text-amber-300" /></div>
            {formJourney.map((item, index) => { const Icon = item.icon; const angle = index * 60 - 150; return <div key={item.id} className="absolute left-1/2 top-1/2" style={{ transform: `rotate(${angle}deg) translateY(-151px) rotate(${-angle}deg) translate(-50%, -50%)` }}><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-slate-700 bg-slate-900/95 text-slate-300 shadow-xl" title={item.title}><Icon className="h-5 w-5" /></div></div> })}
          </div></div>
          <div><div className="mb-5"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-400">Interactive form map</p><h2 className="mt-2 text-2xl font-extrabold text-white">What the evaluation journey covers</h2><p className="mt-2 text-xs leading-5 text-slate-400">The 3D model is based on the information journey used by the Sree Vriddhi evaluation experience instead of showing an unrelated decorative object.</p></div><div className="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">{formJourney.map((item) => { const Icon = item.icon; return <div key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/65 p-3.5 transition-all hover:-translate-y-1 hover:border-amber-400/30"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-amber-400/20 bg-amber-400/5 text-amber-300"><Icon className="h-4 w-4" /></div><div><div className="flex items-center gap-2"><span className="text-[9px] font-extrabold tracking-widest text-amber-400">{item.step}</span><span className="text-xs font-extrabold text-white">{item.title}</span></div><p className="mt-1 text-[10px] leading-4 text-slate-400">{item.detail}</p></div></div></div> })}</div></div>
        </div>
      </section>
      <section className="rounded-[2rem] border border-amber-400/20 bg-slate-950/90 p-5 sm:p-8 shadow-2xl" data-future-tilt><div className="mb-6"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-400">Step 1 · Category</p><h2 className="mt-2 text-2xl font-extrabold text-white">Select the category that best matches your requirement</h2><p className="mt-2 text-xs leading-5 text-slate-400">This selection helps you understand the relevant evaluation path. Select the matching option again inside the official Google Form where requested.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{options.map((item) => { const Icon = item.icon; const isActive = selected === item.id; return <button key={item.id} type="button" onClick={() => setSelected(item.id)} className={`text-left rounded-2xl border p-4 transition-all hover:-translate-y-1 ${isActive ? 'border-amber-400/60 bg-amber-400/10 shadow-lg shadow-amber-500/10' : 'border-slate-800 bg-slate-900/70 hover:border-slate-600'}`}><div className="flex items-start gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${isActive ? 'border-amber-400/40 bg-amber-400/10 text-amber-300' : 'border-slate-700 bg-slate-950 text-slate-400'}`}><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="text-sm font-extrabold text-white">{item.title}</span>{isActive && <Check className="h-4 w-4 text-amber-300" />}</div><p className="mt-1 text-[10px] font-semibold text-amber-200">{item.subtitle}</p><p className="mt-2 text-[11px] leading-5 text-slate-400">{item.description}</p></div></div></button> })}</div></section>
      <section className="rounded-[2rem] border border-amber-400/20 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 overflow-hidden shadow-2xl" data-future-tilt><div className="border-b border-slate-800 px-5 py-5 sm:px-8"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-400">Step 2 · Official Application Form</p><h2 className="mt-2 text-2xl sm:text-3xl font-extrabold text-white">Continue to the Sree Vriddhi Evaluation Form</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">The official form is hosted by Google. We keep it as the source of truth for the live questions, validation and submission.</p></div><div className="px-5 py-10 sm:px-8 sm:py-14"><div className="mx-auto max-w-3xl rounded-[1.75rem] border border-amber-400/20 bg-slate-950/80 p-6 sm:p-10 text-center shadow-[0_0_70px_rgba(245,158,11,.08)]"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl border border-amber-300/30 bg-amber-400/10 shadow-lg shadow-amber-500/10"><FileCheck2 className="h-9 w-9 text-amber-300" /></div><h3 className="mt-6 text-xl sm:text-2xl font-extrabold text-white">Ready to submit your preliminary details?</h3><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-400">You selected <span className="font-bold text-amber-300">{active.title}</span>. Continue to the official Google Form and complete every requested field.</p><button type="button" onClick={openForm} className="mt-7 inline-flex min-w-[240px] items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-amber-400 to-orange-500 px-7 py-4 text-sm font-extrabold text-slate-950 shadow-lg shadow-amber-500/20 transition hover:scale-[1.02] hover:shadow-amber-500/30">Open Evaluation Form <ArrowRight className="h-4 w-4" /></button><p className="mt-4 flex items-center justify-center gap-1.5 text-[11px] text-slate-500"><ExternalLink className="h-3.5 w-3.5" /> Secure Google-hosted form · Opens in this tab</p></div></div></section>
    </div>
  )
}
