import React from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, FileText, ShieldCheck, CheckCircle2 } from 'lucide-react'

const terms = [
  ['1. Understand the Nature of the Opportunity', 'I understand that the opportunity presented by Sree Vriddhi involves the use of my funds under the agreed business arrangement and terms communicated to me.\n\nI understand that I should participate only after independently evaluating whether the arrangement is suitable for my financial situation and personal requirements.'],
  ['2. Returns Are Subject to the Agreed Terms', 'I understand that any interest, payout, or return discussed with me is based on the specific terms of the applicable agreement.\n\nPast discussions, examples, illustrations, or expected returns should not automatically be treated as a guarantee of future performance or payment unless the applicable written agreement and applicable law expressly provide otherwise.'],
  ['3. Capital / Principal Risk', 'I understand that providing funds to any business arrangement involves financial risk. The amount I provide may be exposed to business, operational, liquidity, counterparty, and other risks. I should not commit money that I may immediately need for essential personal or family expenses. The possibility of receiving returns does not eliminate the possibility of financial loss.'],
  ['4. Contract Duration and Withdrawal', 'I understand the agreed contract duration before proceeding. Where the applicable agreement specifies a minimum or non-breakable period, I understand that I should consider the funds committed for that period and should not assume that I can withdraw them whenever I wish. Any early-exit, withdrawal, settlement, or cancellation will be governed by the applicable written agreement.'],
  ['5. No Pressure to Participate', 'I confirm that I am participating voluntarily. I understand that I should not proceed merely because of promotional communication, urgency, limited availability, personal recommendations, or expected returns. I have the opportunity to ask questions and obtain clarification before making my decision.'],
  ['6. Independent Decision', 'I confirm that I have had the opportunity to understand the arrangement, ask questions, and review the relevant terms before proceeding. Sree Vriddhi does not replace my own financial, legal, or tax adviser. Where appropriate, I may seek independent professional advice before committing funds.'],
  ['7. Information Provided by Me', 'I confirm that the personal, financial, banking, identification, and other information submitted by me is accurate and belongs to me. Incorrect or incomplete information may affect the processing of my application or agreement.'],
  ['8. Payment Details', 'Payments, interest credits, settlements, or other financial transactions will be processed only according to the applicable agreed terms. I will verify the recipient/payment details before making any transfer. I will not share my OTP, PIN, CVV, password, or other confidential banking credentials with anyone claiming to represent Sree Vriddhi.'],
  ['9. Regulatory Understanding', 'I understand that I should independently verify the legal and regulatory status of the particular business arrangement before committing funds. Any statement regarding registration, authorization, licensing, protection, guarantee, or regulatory supervision should be relied upon only when supported by appropriate official documentation.'],
  ['10. Final Confirmation', 'I have read and understood the above acknowledgement. I understand that financial returns can involve financial risk, and I am proceeding voluntarily after considering my own circumstances. I have been given an opportunity to ask questions and seek clarification before proceeding. I understand that this acknowledgement does not remove or replace the detailed terms and conditions of the applicable written agreement.'],
]

export default function Terms() {
  return <main className="min-h-screen bg-slate-950 px-4 py-16 text-slate-100 md:px-8">
    <div className="mx-auto max-w-6xl">
      <Link to="/" className="mb-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-amber-300"><ArrowLeft size={15}/> Back to Sree Vriddhi</Link>
      <section className="relative overflow-hidden rounded-[2rem] border border-amber-300/20 bg-gradient-to-br from-slate-900 to-slate-950 p-7 shadow-2xl md:p-12"><div className="absolute -right-16 -top-16 h-60 w-60 rounded-full border border-amber-300/10 [transform:perspective(700px)_rotateX(62deg)_rotateZ(18deg)]"/><div className="relative"><div className="mb-4 flex items-center gap-2 text-xs font-black uppercase tracking-[.24em] text-amber-300"><FileText size={16}/> Please read before proceeding</div><h1 className="font-serif-brand text-4xl font-black leading-tight md:text-6xl">Terms &amp; Conditions — Customer Risk &amp; Policy Acknowledgement</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Please read the business terms and acknowledge before submitting.</p><p className="mt-3 max-w-3xl text-slate-400">At Sree Vriddhi, we believe that every financial decision should be made with <strong className="text-slate-200">clarity, awareness, and mutual understanding.</strong></p></div></section>
      <section className="mt-10"><div className="mb-7 flex items-end justify-between gap-5"><div><span className="text-[10px] font-black uppercase tracking-[.24em] text-amber-300">INTERACTIVE TERMS MAP</span><h2 className="mt-2 font-serif-brand text-3xl font-bold md:text-4xl">Ten decision layers. One clear acknowledgement.</h2></div><ShieldCheck className="hidden text-amber-300 md:block" /></div><div className="grid gap-5 md:grid-cols-2">{terms.map(([title, body], index) => <article key={title} className="group relative overflow-hidden rounded-3xl border border-white/10 bg-slate-900/75 p-6 shadow-xl transition duration-300 hover:-translate-y-1 hover:border-amber-300/40 hover:shadow-amber-950/30"><div className="absolute right-4 top-4 h-20 w-20 rounded-full border border-amber-300/10 transition duration-500 group-hover:scale-125 group-hover:rotate-45"/><div className="relative flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl border border-amber-300/30 bg-amber-300/10 text-sm font-black text-amber-300">{String(index + 1).padStart(2, '0')}</div><div><h3 className="text-lg font-bold text-white">{title}</h3><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-300">{body}</p></div></div></article>)}</div></section>
      <section className="mt-10 rounded-3xl border border-emerald-300/20 bg-emerald-300/[0.05] p-7 md:p-9"><div className="flex items-start gap-4"><CheckCircle2 className="mt-1 shrink-0 text-emerald-300"/><div><h2 className="text-xl font-bold">Final acknowledgement</h2><p className="mt-3 leading-7 text-slate-300">I understand that <strong>financial returns can involve financial risk</strong>, and I am proceeding voluntarily after considering my own circumstances. I have been given an opportunity to ask questions and seek clarification before proceeding.</p><p className="mt-3 text-sm font-semibold text-amber-200">This acknowledgement does not remove or replace the detailed terms and conditions of the applicable written agreement.</p></div></div></section>
    </div>
  </main>
}
